name: master CI/CD

on:
  push:
    branches: [ master ]

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Build Release
      run: dotnet publish -c Release -r linux-x64
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        local-dir: /home/runner/work/daltonsbaker.com-blazor/daltonsbaker.com-blazor/Daltonsbaker.Com/bin/Release/net5.0/publish/wwwroot/
        server: 66.96.162.135
        username: daltonsbaker-deploy
        password: ${{ secrets.daltonsbaker_password }}
