name: master CI/CD

on:
  push:
    branches: [ master ]

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    
    env:
      MAIN_PROJECT: Daltonsbaker.Com
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Build Release
      run: dotnet publish -c Release -r linux-x64
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        local-dir: ${{ github.WORKSPACE }}/${{ env.MAIN_PROJECT }}/bin/Release/net7.0/publish/wwwroot/
        server: ${{ secrets.DEPLOY_SERVER }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
